### ISSUE TITLE
Wiki Deadlinks

### ISSUE THREAD

**Issue by DeerTears** [Shfty/qodot-plugin#103]
All of these links either no longer exist or have since been renamed. Attempting to go to these links will redirect the user to the Wiki Homepage: https://github.com/Shfty/qodot-plugin/wiki

**page with deadlink:** https://github.com/Shfty/qodot-plugin/wiki/2.-Usage
**link-bearing text:** "More information on QodotMap and its properties can be found on the [QodotMap](https://github.com/ShiftyAxel/Qodot/wiki/QodotMap) page."
**attempted link:** https://github.com/ShiftyAxel/Qodot/wiki/QodotMap

**page with deadlink:** https://github.com/Shfty/qodot-plugin/wiki/6.-.map-files
**link-bearing text:** "Any Quake-compatible map editor can be used to generate .map files, but [TrenchBroom](https://github.com/ShiftyAxel/Qodot/wiki/TrenchBroom) is recommended and directly supported."
**attempted link:** https://github.com/ShiftyAxel/Qodot/wiki/TrenchBroom

These were all the deadlinks I could find.

**Comment by Shfty** [comment]
Thanks - these are sorted now. The QodotMap link was to a removed page (now covered by the UI overview in the Usage page), and the TrenchBroom link now points to the correct URL.
