### ISSUE TITLE
How To Setup Qodot On Linux?

### ISSUE THREAD

**Issue by RilDev** [Shfty/qodot-plugin#113]
Good day,

I am very new to Godot development and came across Qodot as being a very good alternative to Blender.

I read the Wiki but I still don't understand what the `Qodot_Trenchbroom_Config_Folder.tres` or how to open it from within Godot or even where to move it.

My goal here is to be able to create a Qodot project in Trench Broom, to export it and to import it into Godot.

Could someone help me out?

Thank you!

**Comment by Pio64** [comment]
The instructions are here, but they are probably incomplete: https://github.com/Shfty/qodot-plugin/wiki/1.-Installation.

1. Clone the repository with its submodules.
2. Install `scons`.
3. Run the `build-x11.sh` script that comes with Qodot.
4. Copy Qodot's `addons` folder into your Godot's game project folder.
5. Open your project in Godot. Go to `Project > Project Settings > Plugins` and enable Qodot.

If it works you, will have additional nodes that you can add to your scene such as `QodotMap`.

**Comment by RilDev** [comment]
Thanks for your help @Pio64!

I was able to install and enable Qodot.

![image](https://user-images.githubusercontent.com/13135150/98237125-b6438100-1f64-11eb-8d08-16c82a8526f1.png)

---

But I still didn't manage to make the game available in TrenchBroom.

![image](https://user-images.githubusercontent.com/13135150/98237271-ef7bf100-1f64-11eb-9e86-435791296b66.png)

I changed the path to my TrenchBroom folder like it says in the documentation and exported the file: [https://github.com/Shfty/qodot-plugin/wiki/7.-TrenchBroom](https://github.com/Shfty/qodot-plugin/wiki/7.-TrenchBroom)

![image](https://user-images.githubusercontent.com/13135150/98238671-091e3800-1f67-11eb-8440-3b60828d310f.png)

The folder for the game "Qodot" was created successfully:

![image](https://user-images.githubusercontent.com/13135150/98238856-50a4c400-1f67-11eb-9b52-b2ecc4fb00f8.png)

Do you know what went wrong?

**Comment by Pio64** [comment]
For me the correct path is: `~/.TrenchBroom/games`. Try putting your exported Qodot folder there.

**Comment by RilDev** [comment]
Thank you it worked!

So for reference (hi future me), here is how I did it:

1. Download TrenchBroom and install it: 

Download it from [TrenchBroom's GitHub release page](https://github.com/TrenchBroom/TrenchBroom/releases/tag/v2020.2). And install it `sudo apt install ./TrenchBroom*.deb`. __Don't install it with `snap` because it doesn't create the `~/.TrenchBroom/games` folder!__

2. In Godot, install the Qodot plugin like in the [docs](https://github.com/Shfty/qodot-plugin/wiki/1.-Installation).
3. Export the Godot game to TrenchBroom like specified in the [docs](https://github.com/Shfty/qodot-plugin/wiki/2.-Usage#exporting-game-definitions-for-trenchbroom). The correct path on Linux is `~/.TrenchBroom/games`.
4. Launch `trenchbroom` and you should see you game there!
 
![image](https://user-images.githubusercontent.com/13135150/98447948-200c8800-2129-11eb-8264-4bed6ce3a803.png)

Tip: Change the name of the game in TrenchBroom in the "Game Name" section of the `qodot_trenchbroom_config_folder.tres` 
 & `qodot_trenchbroom_config_file.tres` files.

![image](https://user-images.githubusercontent.com/13135150/98448019-81ccf200-2129-11eb-8d3d-cf12a849c902.png)

Thanks again for your help @Pio64!
