### ISSUE TITLE
linux (debian) Trenchbroom/games/  folder

### ISSUE THREAD

**Issue by anarchydev** [Shfty/qodot-plugin#118]
Hello,

Please help - where is on linux Trenchbroom/games/  folder? (installed by deb package) i cant make game definition without that location :/

**Comment by VCSocial** [comment]
Try checking ~/.Trenchbroom/games it should be there by default.

**Comment by Shfty** [comment]
No idea - I develop and test on Manjaro with a zip copy of TrenchBroom when needed.

And given that this isn't an issue with either Qodot or TrenchBroom themselves, it's a question better suited to the TrenchBroom Discord than a git issue tracker.
