### ISSUE TITLE
qodot_trenchbroom_config_folder.tres doesn't work unless you have the default "icon.png" in your project

### ISSUE THREAD

**Issue by JamesC01** [Shfty/qodot-plugin#130]
qodot_trenchbroom_config_folder.tres doesn't work if you delete icon.png.

**Comment by Shfty** [comment]
Solution: Don't delete icon.png

**Comment by JamesC01** [comment]
Well I know that. But why assume they're using icon.png? You could use a custom icon and it could be named something different. Relying on something that may or may not be there is bad in my opinion. There's a perfectly good icon.png for qodot in the qodot folder. Couldn't it fall back to that if it can't find res://icon.png, instead of just erroring?

**Comment by JamesC01** [comment]
Hey, could you look into this again? I don't think the plugin should just break if there' no icon.png. If you argue that there should always be an icon, then what about the case where multiple icons are used? I've come across WindowsIcon.png etc. before. I know it's a small issue to encounter, but it'd probably be a small issue to fix, too.

Ignore what I said in my previous comment, it doesn't need to fall back to the qodot icon. Look at Trenchbroom's docs under ["Game Configuration File Syntax"](https://github.com/TrenchBroom/TrenchBroom/blob/master/app/resources/documentation/manual/index.md) It says that the Icon property is optional. Couldn't qodot just not output the icon property if it can't find an icon? It works fine that way with trenchbroom.
