### ISSUE TITLE
Build geometry separated by brushes

### ISSUE THREAD

**Issue by LL2** [Shfty/qodot-plugin#135]
Individual meshes per brushes would be good for the portal occlusion culling (Godot v3.4). Building a single mesh from a entire map has no sense in my opinion.

**Comment by Shfty** [comment]
Qodot batches meshes per-material-per-entity to reduce draw call overhead, which is a major bottleneck for Godot rendering performance. Splitting per-brush is a naive solution that would negatively impact the render performance scaling of mid-to-large maps.

If you need to split brushes, you should do so manually by applying a brush entity class to separate the geometry from the worldspawn entity. This retains draw call optimizations, and leaves split granularity as a choice for the mapper to make.

**Comment by 20kdc** [comment]
Does UV2 wrapping / lightmap baking still occur on brush entities?
