### ISSUE TITLE
Configurable mesh / collision split overrides

### ISSUE THREAD

**Issue by Shfty** [Shfty/qodot-plugin#42]
Specifically func_group and func_detail. From therektafire:

> since func_groups are technically worldspawn as far as QBSP is concerned (and as far as qodot should be concerned as well), func_groups, func_details etc should be combined into single meshes since they are meant to be static level geometry. On the other hand other types of entities would probably be better suited for being imported on a per brush basis, like func_breakable. So what I would do is either add a cfg file to the plugin or an array entry to qodotmap which lists some defaults for which types of things should be imported in which way, and the user can edit it if they want different behavior
> Oh and the same goes for collision as well as the visual model

This mainly seems like it would affect the per-entity node spawning pipeline, since the worldspawn no longer exists after the map file has been parsed into other kinds of geo.

**Comment by ShiftyAxel** [comment]
This should be covered by configurable single / entity / brush splitting, provided that the appropriate overrides for things like func_breakable are easy to define.

**Comment by Shfty** [comment]
The FGD functionality in #8 ties in nicely to this- organizing visual / collision splits by classname will allow for appropriate granularity, and potentially be able to replace the broad-strokes selections currently exposed via QodotMap.
