### ISSUE TITLE
More intuitive class layout for build pipelines

### ISSUE THREAD

**Issue by Shfty** [Shfty/qodot-plugin#56]
Since the setup / visuals / static collision / area collision / lighting build steps already form natural groups, the build pipelines should either be split appropriately (since QodotMap assembles on-demand anyway) or arranged with a new BuildStepGroup class.

I think avoiding a new class is preferable, maybe pipelines themselves need to be renamed to something befitting a smaller group of steps.

Either way, also need to refactor pipeline assembly with a function for combining groups.

**Comment by ShiftyAxel** [comment]
Perhaps turn build pipelines into Resource classes to allow for easy creation in the editor.

**Comment by Shfty** [comment]
No longer relevant following C rewrite.
