### ISSUE TITLE
Float-format support for light color

### ISSUE THREAD

**Issue by kakoeimon** [Shfty/qodot-plugin#58]
In build_entity_spawns.gd color is treated with ints but the default floats is what is needed.

It is like this :
`var red = int(comps[0]) / 255.0`

and must become like this:
`var red = float(comps[0])`

**Comment by ShiftyAxel** [comment]
What map format are you importing @kakoeimon, one targeting an existing game (Quake 1, 2, 3, etc) or an original one created specifically for Godot use?

The light import functionality was modeled around the format used by modern Quake 1 source ports, which uses the Byte format in TrenchBroom: 

![image](https://user-images.githubusercontent.com/1253239/71188348-b0737d00-2278-11ea-8996-a7de3802c49c.png)

I'm open to adding game-specific Entity Spawn presets to ensure the right format gets used for other supported titles (and perhaps one for Godot using floats), but naively making this change to the core code would break the current intended functionality.

**Comment by kakoeimon** [comment]
@ShiftyAxel I use standard quake 1 format, but as it looks like I was using the float option for the light color.

**Comment by ShiftyAxel** [comment]
Will do some research and try to figure out whether any of the TB-supported formats use float for lighting color.

Chances are one or two of them will, so splitting lights out of Entity Spawns and into their own category with a byte/float selection dropdown is probably wise.

**Comment by kakoeimon** [comment]
I was using those maps with quakespasm it was a tc I never completed. Those where Quake 1 Standard maps. 
Trenchbroom can detect if those are float or byte but in the map file there is no hind of what it is.
I was thinking something along those lines.
If the values contain a number higher than one then it is byte.
If the values are floats the it is a float. 

The only downside I can think of this logic is the byte color 1 1 1 but it is very unussual to be considered.

**Comment by Shfty** [comment]
This is fixed as of the latest commit- since the properties come through as strings, I'm having it check for the presence of a decimal point to determine format.

This does mean that floating-point format lights with a color of `1 1 1` will end up being effectively black, but I figure that's an acceptable edge case given that lights default to being white anyway.

**Comment by kakoeimon** [comment]
I think the oposite may be a better solution to the problem. 
Check if it contains a value higher than one if it is then we get the byte color.
I believe byte color of 1 1 1 if very unussual. Float of 1 1 1 it's more common ( I think it is and the default color in Quake for lights.

**Comment by Shfty** [comment]
@kakoeimon Why would you be setting `_color` with a float value of `1 1 1` instead of just creating a light entity without that key?

**Comment by kakoeimon** [comment]
@Shfty Indeed!
