### ISSUE TITLE
Import Half Life goldsrc maps

### ISSUE THREAD

**Issue by fire** [Shfty/qodot-plugin#63]
Hi, do you know if it is possible to load the source of Half Life maps?

https://unknownworlds.com/ns2/natural-selection-source-code-released/

https://github.com/ENSL/NS

I can't find a .map yet, but I'm looking.

**Comment by Shfty** [comment]
GoldSrc maps should work since they're based on the Quake 1 format, with some changes to UVhandling that are automatically accounted for in Qodot.
