### ISSUE TITLE
When importing single-cube brushes, 24 verts are created when 8 should suffice

### ISSUE THREAD

**Issue by javawag** [Shfty/qodot-plugin#64]
Importing a brush with a single cube/cuboid should ideally generated a convex hull which has 8 verts (1 for each corner). However, currently it's creating 24 verts (maybe 8 verts x 3 axes?) which could be inefficient.

Creating a `MeshInstance` node with a `CubeMesh` and getting Godot to create a convex hull of this does correctly yield a convex hull with 8 verts.

**Comment by javawag** [comment]
See screenshot at: https://imgur.com/a/vx2QdB6

**Comment by Shfty** [comment]
This is fixed in the latest commit- the de-duplication code was checking un-transformed vertices against transformed ones, and thus ultimately doing nothing.

Testing with the default cube map generated by TB, the expected 8 vertices are coming through instead of 24.
