### ISSUE TITLE
Mesh build fails when using material override

### ISSUE THREAD

**Issue by sunkper** [Shfty/qodot-plugin#67]
**Versions:**
Qodot 1.5.x
Godot 3.2 RC1

**Description**
Mesh build fails when using Material Mesh pipelines and material override.

**Log:**
> Building map...
> 
> Parsing map file...
> Done in 0.003 seconds.
> 
> Map textures:
> [
> 	0: __TB_empty
> 	1: materials/WindowGlass
> 	2: materials/tangent-test
> 	3: pbr/Dirt01
> ]
> 
> Error: Requested parameter material_meshes not present in context for build step material_meshes
>  res://addons/qodot/src/build/step/build_meshes/build_material_meshes.gd:86 - Invalid get index 'material_meshes' (on base: 'Dictionary').
> Error: Requested parameter area_collision_shapes not present in context for build step area_collision_shapes
>
> Build complete after 0.29 seconds.

**Sample Project:**
[MaterialOverrides.zip](https://github.com/Shfty/qodot-plugin/files/4084740/MaterialOverrides.zip)

**Comment by sunkper** [comment]
Interestingly it works on this project.

[towers_test.zip](https://github.com/Shfty/qodot-plugin/files/4127063/towers_test.zip)

**Comment by Shfty** [comment]
This is fixed in the latest commit to master- the material meshes build step was handling ShaderMaterial instances incorrectly and trying to query them for a SpatialMaterial albedo texture.

I've added some error checking and the sample project now compiles correctly.
