### ISSUE TITLE
[1.5.5] Wrong normal when you make bevel-like shape?

### ISSUE THREAD

**Issue by sunkper** [Shfty/qodot-plugin#72]
**Versions**
Qodot 1.5.5 / Godot 3.2

**Description**
![bevel_01](https://user-images.githubusercontent.com/4294611/73914617-feae0f80-48fc-11ea-81c7-d2a78c14fe73.png)
![bevel_03](https://user-images.githubusercontent.com/4294611/73914632-079ee100-48fd-11ea-839f-4d76bc62dac5.png)

As you can see it happens when two beveled edges meet. It happens since 1.5.5. I didn't use smooth shading.

**Sample Project**:
[BevelShape.zip](https://github.com/Shfty/qodot-plugin/files/4163667/BevelShape.zip)

**Comment by Shfty** [comment]
Ah, this would be down to an optimization I put in place for the vertex generation while adding the smoothed normal functionality. It shouldn't have any dependency on the new feature, so I'll roll it back shortly.

**Comment by Shfty** [comment]
Fixed in 1.5.6
