### ISSUE TITLE
Add option to use TrenchBroom groups to establish scene tree hierarchy

### ISSUE THREAD

**Issue by Shfty** [Shfty/qodot-plugin#78]
Suggested by Corruptinator on the discord- since TrenchBroom groups can be nested, they can be used to establish a node hierarchy during build time, which would enable easier control over local-space transforms like rotation.

**Comment by Corruptinator** [comment]
And add to that easier for door rotations

**Comment by Shfty** [comment]
Implemented during the C rewrite.
