### ISSUE TITLE
TrenchBroom game definition export from Godot

### ISSUE THREAD

**Issue by Shfty** [Shfty/qodot-plugin#8]
Ideally the user should be able to export a ready-to-go TrenchBroom config for their game, complete with a custom set of entity and face definitions defined within the editor.

This would require a custom resource for the game definition containing an icon (to be resized to 32x32), the data for GameConfig.cfg, and the data for a game-specific .fgd file.

FGD stands for 'Forge Game Data' and is an extension for Hammer's game definition files. Spec is available here:
https://developer.valvesoftware.com/wiki/FGD

**Comment by distractedmosfet** [comment]
I'm looking at writing a fgd generator for my own purposes, so I might as well have a go at one I can share back with the project. I've played around with writing fgds a little and feel reasonably confident that I could figure something out. But if I'm looking at sharing it back I'm curious for your opinion on what I'm thinking:

The most natural way to me would be the idea that each entity in the definition file matches to a resource location for a given scene, and upon importing Qodot's QodotBuildEntitySpawns would take the entity class name, look up the corresponding scene path, and instances that scene as a child node.

Now, the other part to be considered is how the user defines their entity set in the first place. I'm thinking of going with something like how Godot handles TileSet definitions, for consistency: you make a scene that represents a entity definition file, each first-level child node of the parent is of a particular type; let's call it QodotEntityDefintion. The name you use for the node is the default resulting class name. The definition type exports some variables: classname override, description, colour, scene path. In terms of useful visual elements, getting a model showing in TrenchBroom is theoretically possible but I'm going to go ahead and put this in the "some other day" basket. Icons would be nice, and fgd itself seems to support them, [but TrenchBroom does not yet.](https://github.com/kduske/TrenchBroom/issues/2882) The idea of using a scene file to define the entity set is probably the part I'm most curious for your feedback on. It's a little odd; some more programming-centric people would say "Why not just a json-file or something?", but as mentioned I think it's more consistent with other parts of Godot, less scary to non-programmers, and with tscn tracks nicely enough in git anyway.

It'd be nice to autodetect exported variables on the entity scene root and port over the ones that seem representable in fgd, but I'm not actually sure that's possible to determine in GDScript right now. An approach to getting exported variables through that may work is to add to the entity definition node type an array of strings and have you type in the names of the properties you want to be editable in TrenchBroom, then I _think_ via PackedScene.get_state().get_node_property_value we might be able to get the Script of the parent node out, then potentially use the [new APIs provided in 3.2](https://github.com/godotengine/godot/pull/31021) to iterate over the properties, get their types, use that to infer the type to use in the fgd. Raise errors on bad property name/type.

Anyway. That's what I'm thinking. I hope that ramble was understandable. Does that sound like something you'd merge in? Advise/feedback?

**Comment by Shfty** [comment]
This is now partly complete thanks to @distractedmosfet's work on exporting point entities.

Brush entities need to be looked at next. Self-note for future reference: there's some relevant discussion in #66 around how those would be implemented.

**Comment by Shfty** [comment]
The FGD export side of this commit is now covered, following the refactor in the latest commits.

Next up will be to figure out a proper, flexible map file > godot entity workflow.

**Comment by Shfty** [comment]
As of the latest commits, brush entities are now working. You can define a FGD entry for them with arbitrary properties, as well as settings for merging with worldspawn and optional visuals / collision, export them to TrenchBroom, build something with them, then import the map back and have the brush entities built with appropriately attached scripts, with an interface for responding to changes in the property dictionary.

Next to do is tidying up the visual / collision build structure, as brush entities are hard-coded to use material mesh visuals and convex per-brush collision at the moment. Need to have a think and figure out the best way to align it with the Quake way of doing things.

**Comment by Shfty** [comment]
The build structure has been refactored, which has improved build step code bloat considerably, but invalid collider bugs have started cropping up.

They don't appear to be fatal for an exported build, but they cause the editor to crash when rebuilding the same map multiple times. Need to troubleshoot this before continuing.

After that's fixed, the next step will be to create a basic TrenchBroom game definition export system as a superset of the FGD export.

**Comment by Shfty** [comment]
Turns out it wasn't the same bug as before, but rather an amalgam of new bugs. The hastily-patched tree hierarchy composition code was causing references to invalid objects to get held, thus causing editor crashes on subsequent map builds.

The invalid mesh issue is separate, and non-fatal. Running the example map through TrenchBroom's issue fixup has reduced it down to a single instance of the following:
```
ERROR: build: Condition "O == __null" is true. Continuing.
   At: core/math/quick_hull.cpp:402
```

Which occurs only at build-time, rather than runtime. The collision meshes themselves appear to be fine, so for now I'm happy to consider it a non-issue.

**Comment by Shfty** [comment]
This feature is now complete as of the latest commit- TrenchBroom config folders can be generated with an icon, GameConfig.cfg (with appropriate tags, flags and FGD fields), and multiple FGD files.
