### ISSUE TITLE
Missing .dll for Windows? Failed to install from AssetLib

### ISSUE THREAD

**Issue by tjanok** [Shfty/qodot-plugin#89]
When using 3.2 w/32bit (or 64bit). Installing into a fresh project, the addon fails to install and the console dumps "can't open dynamic library ..../libqodot.dll".
![image](https://user-images.githubusercontent.com/8595236/76104401-48902100-5fa1-11ea-9573-459cf8cd3f76.png)

**Comment by Shfty** [comment]
This is down to the Qodot asset library only being able to download repo source zips, rather than releases.

I've added an automatic dependency downloader to the plugin and set the CI providers up to automate tagged releases. Should prevent the issue going forward.
