### ISSUE TITLE
Port business logic to a native C++ DLL and integrate with GDNative

### ISSUE THREAD

**Issue by Shfty** [Shfty/qodot-plugin#9]
Since the geometry generation code is a brute-force algorithm across potentially large datasets (a.k.a. complex many-faced brushes), porting it to GDNative would be good for performance. This also opens up the possibility for the GDScript-side code to be strictly engine integration, making prospective ports to other engines easier.

This might conflict with the #4? Unsure of the status of multi-threading + GDNative, though I suppose the DLL could handle all of that native-side without involving Godot.

**Comment by Wavesonics** [comment]
There is something really awesome about how accessible it all is if it;s in GDScript. Zero setup for someone to pick it apart and modify it. Certainly if performance seems to be an issue this is worth it though.

**Comment by Shfty** [comment]
Done.
